### ISSUE TITLE
Clean logging during Service Instance creation failure

### ISSUE THREAD

**Issue by pshahzeb** [vmware/vsphere-storage-for-docker#1896]
When si creation is failed (hostd is down). The log dump is a mess.
This is valid case and we retry to create si (connect to hostd). However, the log during failure needs to be systematically dumped.

Right now its something like
```
09/22/17 16:53:06 928247 [VMChangeListener] [ERROR  ] Failed to create the local Service Instance as 'dcui', continuing... :
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1163, in get_si
    _service_instance.CurrentTime()
AttributeError: 'NoneType' object has no attribute 'CurrentTime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys/lib64/python3.5/site-packages/pyVim/connect.py", line 323, in __Login
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys/lib64/python3.5/site-packages/pyVmomi/VmomiSupport.py", line 557, in <lambda>
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys/lib64/python3.5/site-packages/pyVmomi/VmomiSupport.py", line 363, in _InvokeMethod
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys/lib64/python3.5/site-packages/pyVmomi/SoapAdapter.py", line 1338, in InvokeMethod
http.client.HTTPException: 503 Service Unavailable (Failed to connect to endpoint: [N7Vmacore4Http16LocalServiceSpecE:0x05b2e8b8] _serverNamespace = /sdk action = Allow _port = 8307)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1146, in connectLocalSi
    version=newestVersions.Get('vim'))
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys/lib64/python3.5/site-packages/pyVim/connect.py", line 242, in Connect
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys/lib64/python3.5/site-packages/pyVim/connect.py", line 327, in __Login
pyVmomi.VmomiSupport.vim.fault.HostConnectFault: (vim.fault.HostConnectFault) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '503 Service Unavailable (Failed to connect to endpoint: [N7Vmacore4Http16LocalServiceSpecE:0x05b2e8b8] _serverNamespace = /sdk action = Allow _port = 8307)',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
```

**Comment by shuklanirdesh82** [comment]
I guess this is expected behavior.

> However, the log during failure needs to be systematically dumped.

@pshahzeb can you add some more detail about "systematically dumped."?
